### YamlMime:ManagedReference
items:
- uid: DeckSurf.SDK.Util.ConfigurationHelper
  commentId: T:DeckSurf.SDK.Util.ConfigurationHelper
  id: ConfigurationHelper
  children:
  - DeckSurf.SDK.Util.ConfigurationHelper.#ctor
  - DeckSurf.SDK.Util.ConfigurationHelper.GetProfile(System.String)
  - DeckSurf.SDK.Util.ConfigurationHelper.GetProfilePath(System.String)
  - DeckSurf.SDK.Util.ConfigurationHelper.WriteToConfiguration(System.String,System.Int32,DeckSurf.SDK.Models.CommandMapping)
  langs:
  - csharp
  name: ConfigurationHelper
  nameWithType: DeckSurf.SDK.Util.ConfigurationHelper
  fullName: DeckSurf.SDK.Util.ConfigurationHelper
  type: Class
  assemblies:
  - DeckSurf.SDK
  namespace: DeckSurf.SDK.Util
  summary: Class that is used to manage DeckSurf configuration files.
  syntax:
    content: public class ConfigurationHelper
    content.csharp: public class ConfigurationHelper
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  modifiers.csharp:
  - public
  monikers:
  - net9.0
  _op_AssemblyMonikerMapping:
    DeckSurf.SDK:
    - net9.0
- uid: DeckSurf.SDK.Util.ConfigurationHelper.#ctor
  commentId: M:DeckSurf.SDK.Util.ConfigurationHelper.#ctor
  id: '#ctor'
  parent: DeckSurf.SDK.Util.ConfigurationHelper
  langs:
  - csharp
  name: ConfigurationHelper()
  nameWithType: ConfigurationHelper.ConfigurationHelper()
  fullName: DeckSurf.SDK.Util.ConfigurationHelper.ConfigurationHelper()
  type: Constructor
  assemblies:
  - DeckSurf.SDK
  namespace: DeckSurf.SDK.Util
  syntax:
    content: public ConfigurationHelper ();
    parameters: []
    content.csharp: public ConfigurationHelper ();
  overload: DeckSurf.SDK.Util.ConfigurationHelper.#ctor*
  exceptions: []
  modifiers.csharp:
  - public
  monikers:
  - net9.0
- uid: DeckSurf.SDK.Util.ConfigurationHelper.GetProfile(System.String)
  commentId: M:DeckSurf.SDK.Util.ConfigurationHelper.GetProfile(System.String)
  id: GetProfile(System.String)
  parent: DeckSurf.SDK.Util.ConfigurationHelper
  langs:
  - csharp
  name: GetProfile(String)
  nameWithType: ConfigurationHelper.GetProfile(String)
  fullName: DeckSurf.SDK.Util.ConfigurationHelper.GetProfile(String)
  type: Method
  assemblies:
  - DeckSurf.SDK
  namespace: DeckSurf.SDK.Util
  summary: Gets the profile object for a given profile name.
  syntax:
    content: public static DeckSurf.SDK.Models.ConfigurationProfile GetProfile (string profile);
    parameters:
    - id: profile
      type: System.String
      description: Name of the profile.
    return:
      type: DeckSurf.SDK.Models.ConfigurationProfile
      description: Object representing the DeckSurf configuration profile.
    content.csharp: public static DeckSurf.SDK.Models.ConfigurationProfile GetProfile (string profile);
  overload: DeckSurf.SDK.Util.ConfigurationHelper.GetProfile*
  exceptions: []
  modifiers.csharp:
  - public
  - static
  monikers:
  - net9.0
- uid: DeckSurf.SDK.Util.ConfigurationHelper.GetProfilePath(System.String)
  commentId: M:DeckSurf.SDK.Util.ConfigurationHelper.GetProfilePath(System.String)
  id: GetProfilePath(System.String)
  parent: DeckSurf.SDK.Util.ConfigurationHelper
  langs:
  - csharp
  name: GetProfilePath(String)
  nameWithType: ConfigurationHelper.GetProfilePath(String)
  fullName: DeckSurf.SDK.Util.ConfigurationHelper.GetProfilePath(String)
  type: Method
  assemblies:
  - DeckSurf.SDK
  namespace: DeckSurf.SDK.Util
  summary: Returns the fully qualified path to a given DeckSurf configuration profile.
  syntax:
    content: public static string GetProfilePath (string name);
    parameters:
    - id: name
      type: System.String
      description: Name of the profile.
    return:
      type: System.String
      description: Fully qualified path to the profile JSON file.
    content.csharp: public static string GetProfilePath (string name);
  overload: DeckSurf.SDK.Util.ConfigurationHelper.GetProfilePath*
  exceptions: []
  modifiers.csharp:
  - public
  - static
  monikers:
  - net9.0
- uid: DeckSurf.SDK.Util.ConfigurationHelper.WriteToConfiguration(System.String,System.Int32,DeckSurf.SDK.Models.CommandMapping)
  commentId: M:DeckSurf.SDK.Util.ConfigurationHelper.WriteToConfiguration(System.String,System.Int32,DeckSurf.SDK.Models.CommandMapping)
  id: WriteToConfiguration(System.String,System.Int32,DeckSurf.SDK.Models.CommandMapping)
  parent: DeckSurf.SDK.Util.ConfigurationHelper
  langs:
  - csharp
  name: WriteToConfiguration(String, Int32, CommandMapping)
  nameWithType: ConfigurationHelper.WriteToConfiguration(String, Int32, CommandMapping)
  fullName: DeckSurf.SDK.Util.ConfigurationHelper.WriteToConfiguration(String, Int32, CommandMapping)
  type: Method
  assemblies:
  - DeckSurf.SDK
  namespace: DeckSurf.SDK.Util
  summary: Stores the DeckSurf configuration profile.
  syntax:
    content: public static DeckSurf.SDK.Models.ConfigurationProfile WriteToConfiguration (string profile, int deviceIndex, DeckSurf.SDK.Models.CommandMapping mapping);
    parameters:
    - id: profile
      type: System.String
      description: Name of the profile.
    - id: deviceIndex
      type: System.Int32
      description: Zero-based index of the Stream Deck device associated with a profile.
    - id: mapping
      type: DeckSurf.SDK.Models.CommandMapping
      description: Object representing buttons mapped to plugins and commands.
    return:
      type: DeckSurf.SDK.Models.ConfigurationProfile
      description: Object representing the DeckSurf configuration profile.
    content.csharp: public static DeckSurf.SDK.Models.ConfigurationProfile WriteToConfiguration (string profile, int deviceIndex, DeckSurf.SDK.Models.CommandMapping mapping);
  overload: DeckSurf.SDK.Util.ConfigurationHelper.WriteToConfiguration*
  exceptions: []
  modifiers.csharp:
  - public
  - static
  monikers:
  - net9.0
references:
- uid: DeckSurf.SDK.Util
  commentId: N:DeckSurf.SDK.Util
  isExternal: false
  name: DeckSurf.SDK.Util
  nameWithType: DeckSurf.SDK.Util
  fullName: DeckSurf.SDK.Util
  type: namespace
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: DeckSurf.SDK.Util.ConfigurationHelper.#ctor
  parent: DeckSurf.SDK.Util.ConfigurationHelper
  isExternal: false
  name: ConfigurationHelper()
  nameWithType: ConfigurationHelper.ConfigurationHelper()
  fullName: DeckSurf.SDK.Util.ConfigurationHelper.ConfigurationHelper()
  type: constructor
- uid: DeckSurf.SDK.Util.ConfigurationHelper.GetProfile(System.String)
  parent: DeckSurf.SDK.Util.ConfigurationHelper
  isExternal: false
  name: GetProfile(String)
  nameWithType: ConfigurationHelper.GetProfile(String)
  fullName: DeckSurf.SDK.Util.ConfigurationHelper.GetProfile(String)
  type: method
- uid: DeckSurf.SDK.Models.ConfigurationProfile
  parent: DeckSurf.SDK.Models
  isExternal: false
  name: ConfigurationProfile
  nameWithType: ConfigurationProfile
  fullName: DeckSurf.SDK.Models.ConfigurationProfile
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: DeckSurf.SDK.Util.ConfigurationHelper.GetProfilePath(System.String)
  parent: DeckSurf.SDK.Util.ConfigurationHelper
  isExternal: false
  name: GetProfilePath(String)
  nameWithType: ConfigurationHelper.GetProfilePath(String)
  fullName: DeckSurf.SDK.Util.ConfigurationHelper.GetProfilePath(String)
  type: method
- uid: DeckSurf.SDK.Util.ConfigurationHelper.WriteToConfiguration(System.String,System.Int32,DeckSurf.SDK.Models.CommandMapping)
  parent: DeckSurf.SDK.Util.ConfigurationHelper
  isExternal: false
  name: WriteToConfiguration(String, Int32, CommandMapping)
  nameWithType: ConfigurationHelper.WriteToConfiguration(String, Int32, CommandMapping)
  fullName: DeckSurf.SDK.Util.ConfigurationHelper.WriteToConfiguration(String, Int32, CommandMapping)
  type: method
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: DeckSurf.SDK.Models.CommandMapping
  parent: DeckSurf.SDK.Models
  isExternal: false
  name: CommandMapping
  nameWithType: CommandMapping
  fullName: DeckSurf.SDK.Models.CommandMapping
- uid: DeckSurf.SDK.Util.ConfigurationHelper.#ctor*
  commentId: Overload:DeckSurf.SDK.Util.ConfigurationHelper.#ctor
  parent: DeckSurf.SDK.Util.ConfigurationHelper
  isExternal: false
  name: ConfigurationHelper
  nameWithType: ConfigurationHelper.ConfigurationHelper
  fullName: DeckSurf.SDK.Util.ConfigurationHelper.ConfigurationHelper
  monikers:
  - net9.0
  type: constructor
- uid: DeckSurf.SDK.Util.ConfigurationHelper.GetProfile*
  commentId: Overload:DeckSurf.SDK.Util.ConfigurationHelper.GetProfile
  parent: DeckSurf.SDK.Util.ConfigurationHelper
  isExternal: false
  name: GetProfile
  nameWithType: ConfigurationHelper.GetProfile
  fullName: DeckSurf.SDK.Util.ConfigurationHelper.GetProfile
  monikers:
  - net9.0
  type: method
- uid: DeckSurf.SDK.Util.ConfigurationHelper.GetProfilePath*
  commentId: Overload:DeckSurf.SDK.Util.ConfigurationHelper.GetProfilePath
  parent: DeckSurf.SDK.Util.ConfigurationHelper
  isExternal: false
  name: GetProfilePath
  nameWithType: ConfigurationHelper.GetProfilePath
  fullName: DeckSurf.SDK.Util.ConfigurationHelper.GetProfilePath
  monikers:
  - net9.0
  type: method
- uid: DeckSurf.SDK.Util.ConfigurationHelper.WriteToConfiguration*
  commentId: Overload:DeckSurf.SDK.Util.ConfigurationHelper.WriteToConfiguration
  parent: DeckSurf.SDK.Util.ConfigurationHelper
  isExternal: false
  name: WriteToConfiguration
  nameWithType: ConfigurationHelper.WriteToConfiguration
  fullName: DeckSurf.SDK.Util.ConfigurationHelper.WriteToConfiguration
  monikers:
  - net9.0
  type: method
